export struct ArcData {
    color: color,
    current: float,
    max: float,
    unit: string,
}

export component ArcProgressBar inherits Rectangle {
    in property <[ArcData]> arcs;
    in property <string> center-text-primary;
    in property <string> center-text-secondary;
    
    width: 250px;
    height: 175px;

    property <float> width-px: root.width / 1px;
    property <float> height-px: root.height / 1px;

    property <float> stroke-width: 14.0;
    // ===============================
    // Inactive Arcs (background arcs)
    // ===============================
    for arcs[index] in root.arcs : Rectangle {
        //This will create the spacing after each arc iteration
        property <length> container-radius: (parent.width / 2) - 10px - (index * 20px); 
        
        // Make the container progress-angle rectangle instead of progress-angle square to avoid
        // graphic engine stretching or deforming the arch
        width: 2 * container-radius;
        height: container-radius;
        
        // Center it horizontally and align it on the same base
        x: (parent.width - self.width) / 2;
        y: parent.height - self.height - 50px;

        Path {
            width: 100%; height: 100%;
            stroke: #313244;
            stroke-width: 14px;
            fill: transparent;

            // DO NOT REMOVE!! Without it, progress-angle slight change in resolution could end up deforming the arcs
            // This prevents Slint from stretching to 'better' fit inside container
            viewbox-width: self.width / 1px;
            viewbox-height: self.height / 1px;

            property <float> width-px: self.width / 1px;
            property <float> height-px: self.height / 1px;
            property <float> stroke-half: 7.0;

            // Start drawing from the left
            MoveTo { 
                x: stroke-half; 
                y: height-px - stroke-half; 
            }
            // Finish drawing in the right
            ArcTo {
                radius-x: width-px / 2 - stroke-half;
                radius-y: height-px - stroke-half;
                x: width-px - stroke-half;
                y: height-px - stroke-half;
                sweep: true; 
            }
        }
    }
    // ===============================
    // Active Arcs (dynamic progress)
    // ===============================
    for arcs[index] in root.arcs : Rectangle {
        // Same container alignment
        property <length> container-radius: (parent.width / 2) - 10px - (index * 20px); 
    
        width: 2 * container-radius; 
        height: container-radius;
        x: (parent.width - self.width) / 2;
        y: parent.height - self.height - 50px;

        Path {
            width: 100%; 
            height: 100%;
            // DO NOT REMOVE!! Without it, progress-angle slight change in resolution could end up deforming the arcs
            // This prevents Slint from stretching to 'better' fit inside container
            viewbox-width: self.width / 1px;
            viewbox-height: self.height / 1px;

            property <float> progress: arcs.max > 0 ? min(1.0, max(0.0, arcs.current / arcs.max)) : 0;
            
            // If it's '0' we make the arc transparent to avoid visual bugs
            stroke: progress > 0 ? arcs.color : transparent;
            stroke-width: 14px; fill: transparent;

            property <float> width-px: self.width / 1px;
            property <float> height-px: self.height / 1px;
            property <float> half-stroke: 7.0;
            property <float> path-radius: width-px / 2 - half-stroke;

            property <angle> progress-angle: 180deg - (progress * 180deg);

            // Start drawing from the left
            MoveTo { 
                x: half-stroke;
                y: height-px - half-stroke; 
            }
            // Finish drawing in the right
            ArcTo {
                radius-x: path-radius; 
                radius-y: path-radius;
                x: (width-px / 2) + path-radius * cos(progress-angle);
                y: (height-px - half-stroke) - path-radius * sin(progress-angle);
                sweep: true;
            }
        }
    }
    
    // Center text
    VerticalLayout {
        alignment: end;
        padding-bottom: 25px;
        spacing: 1px;
        
        Text {
            text: root.center-text-primary;
            font-size: 34px;
            font-weight: 800;
            color: #cdd6f4;
            horizontal-alignment: center;
            vertical-alignment: bottom;
        }
        Text {
            text: root.center-text-secondary;
            font-size: 14px;
            color: #bac2de;
            horizontal-alignment: center;
            vertical-alignment: bottom;
        }
    }

    // Remaining consumption log
    HorizontalLayout {
        y: parent.height - 20px;
        width: parent.width + 100px;
        alignment: space-around;

        for arc in root.arcs : HorizontalLayout {
            spacing: 6px;

            VerticalLayout {
                Rectangle {
                    width: 10px;
                    height: 10px;
                    border-radius: 5px;
                    background: arc.color;
                }
            }
            VerticalLayout {
                alignment: start;
                Text {
                    text: max(0, round(arc.max - arc.current)) + arc.unit + " to go";
                    color: #bac2de;
                    font-size: 16px;
                    font-weight: 600;
                }
            }
        }
    }
}

