export struct ArcData {
    color: color,
    current: float,
    max: float,
}

export component ArcProgressBar inherits Rectangle {
    in property <[ArcData]> arcs;
    in property <string> center-text-primary;
    in property <string> center-text-secondary;
    
    width: 250px;
    height: 140px;

    property <float> w: root.width / 1px;
    property <float> h: root.height / 1px;

    property <float> stroke-width: 14.0;
    // ===============================
    // Inactive Arcs (background arcs)
    // ===============================
    for arcs[index] in root.arcs : Rectangle {
        //This will create the spacing after each arc iteration
        property <length> r: (parent.width / 2) - 10px - (index * 20px); 
        
        // Make the container a rectangle instead of a square to avoid
        // graphic engine stretching or deforming the arch
        width: 2 * r;
        height: r;
        
        // Center it horizontally and align it on the same base
        x: (parent.width - self.width) / 2;
        y: parent.height - self.height - 15px;

        Path {
            width: 100%; height: 100%;
            stroke: #313244;
            stroke-width: 14px;
            fill: transparent;

            // DO NOT REMOVE!! Without it, a slight change in resolution could end up deforming the arcs
            // This prevents Slint from stretching to 'better' fit inside container
            viewbox-width: self.width / 1px;
            viewbox-height: self.height / 1px;

            property <float> w: self.width / 1px;
            property <float> h: self.height / 1px;
            property <float> stroke-half: 7.0;

            // Start drawing from the left
            MoveTo { 
                x: stroke-half; 
                y: h - stroke-half; 
            }
            // Finish drawing in the right
            ArcTo {
                radius-x: w / 2 - stroke-half;
                radius-y: h - stroke-half;
                x: w - stroke-half;
                y: h - stroke-half;
                sweep: true; 
            }
        }
    }
    // ===============================
    // Active Arcs (dynamic progress)
    // ===============================
    for arcs[index] in root.arcs : Rectangle {
        // Same container alignment
        property <length> r: (parent.width / 2) - 10px - (index * 20px); 
    
        width: 2 * r; 
        height: r;
        x: (parent.width - self.width) / 2;
        y: parent.height - self.height - 15px;

        Path {
            width: 100%; 
            height: 100%;
            // DO NOT REMOVE!! Without it, a slight change in resolution could end up deforming the arcs
            // This prevents Slint from stretching to 'better' fit inside container
            viewbox-width: self.width / 1px;
            viewbox-height: self.height / 1px;

            property <float> progress: arcs.max > 0 ? min(1.0, max(0.0, arcs.current / arcs.max)) : 0;
            
            // If it's '0' we make the arc transparent to avoid visual bugs
            stroke: progress > 0 ? arcs.color : transparent;
            stroke-width: 14px; fill: transparent;

            property <float> w: self.width / 1px;
            property <float> h: self.height / 1px;
            property <float> sh: 7.0;
            property <float> rad: w / 2 - sh;

            property <angle> a: 180deg - (progress * 180deg);

            // Start drawing from the left
            MoveTo { 
                x: sh;
                y: h - sh; 
            }
            // Finish drawing in the right
            ArcTo {
                radius-x: rad; 
                radius-y: rad;
                x: (w / 2) + rad * cos(a);
                y: (h - sh) - rad * sin(a);
                sweep: true;
            }
        }
    }
    
    // Center text
    VerticalLayout {
        alignment: end;
        padding: -10px;
        spacing: 1px;
        
        Text {
            text: root.center-text-primary;
            font-size: 34px;
            font-weight: 800;
            color: #cdd6f4;
            horizontal-alignment: center;
            vertical-alignment: bottom;
        }
        Text {
            text: root.center-text-secondary;
            font-size: 14px;
            color: #bac2de;
            horizontal-alignment: center;
            vertical-alignment: bottom;
        }
    }
}

