import {TabItem} from "tab_item.slint";

export component Footer inherits Rectangle {
    // Keep indices aligned with the tab content in app.slint.
    in-out property <int> active-tab: 0;

    height: 70px;
    background: #11111b;
    // Rounded top corners to look aesthetically pleasing
    border-top-left-radius: 18px;
    border-top-right-radius: 18px;

    HorizontalLayout {
        alignment: space-around;
        padding-top: 15px;
        padding-bottom: 15px;

        TabItem {
            icon: @image-url("../icons/home.svg");
            active: root.active-tab == 0;
            clicked => { root.active-tab = 0; }
        }
        TabItem {
            icon: @image-url("../icons/star.svg");
            active: root.active-tab == 1;
            clicked => { root.active-tab = 1; }
        }
        TabItem {
            icon: @image-url("../icons/chart-pie-3.svg");
            active: root.active-tab == 2;
            clicked => { root.active-tab = 2; }
        }
        TabItem {
            icon: @image-url("../icons/settings.svg");
            active: root.active-tab == 3;
            clicked => { root.active-tab = 3; }
        }
    }
}
