// ---PoC--- \\
// Will add backend to read camera later


export component ScannerOverlay inherits Rectangle {
    in property <string> status-text: "Scanning";
    callback close();

    background: rgba(24, 24, 37, 0.95);
    
    // It has no other use other than grabbing touches so the daily log list 
    // can't be scrolled while scanner runs
    TouchArea {}

    VerticalLayout {
        alignment: center;
        spacing: 40px;

        Text {
            text: root.status-text;
            font-size: 22px;
            font-weight: 700;
            color: #cdd6f4;
            horizontal-alignment: center;
        }

        //Viewfinder
        HorizontalLayout {
            alignment: center;

            Rectangle {
                width: 250px;
                height: 180px;
                border-width: 4px;
                border-color: #a6e3a1;
                border-radius: 16px;
                background: transparent;

                // Red 'laser' line (purely aesthetic)
                Rectangle {
                    width: 96%;
                    height: 2px;
                    background: #d46182;
                    y: parent.height / 2;
                    drop-shadow-blur: 8px;
                    drop-shadow-color: #d46182;
                }
            }
        }

        // Close button
        HorizontalLayout {
            alignment: center;

            Rectangle {
                width: 130px;
                height: 45px;
                background: #cdd6f4;
                border-radius: 22px;

                Text {
                    text: "Cancel";
                    color: #11111b;
                    font-weight: 700;
                    font-size: 16px;
                    horizontal-alignment: center;
                    vertical-alignment: center;
                }

                TouchArea {
                    clicked => { root.close(); }
                }
            }
        }
    }
}