// --- UI IS NOT SCALABLE YET --- \\
// ---   PROOF OF CONCEPT  --- \\

import { Footer } from "components/footer.slint";
import { HomeTab } from "tabs/home_tab.slint";
import { ScanTab } from "tabs/scan_tab.slint";
import { ChartTab } from "tabs/chart_tab.slint";
import { SettingsTab } from "tabs/settings_tab.slint";

export component MainWindow inherits Window {
    width: 400px;
    height: 800px;
    title: "Ultimate Macro";
    background: #1e1e2e;

    in-out property <int> active-tab: 0;

    VerticalLayout {
        Rectangle {
            if (root.active-tab == 0) : HomeTab {}
            if (root.active-tab == 1) : ScanTab {}
            if (root.active-tab == 2) : ChartTab {}
            if (root.active-tab == 3) : SettingsTab {}
        }
        // Footer
        Footer {
            active-tab <=> root.active-tab;
        }
    }
}